class AuthException(Exception):
    pass

class RefreshException(Exception):
    pass